# This route is for the Symfony-based GestionRdvController.
# The main configuration page uses ModuleAdminController and doesn't need a route here.
admin_dimsymphony_gestionrdv_index:
  path: /modules/dimsymfony/gestionrdv
  controller: 'DimSymfony\Controller\Admin\DimSymfonyGestionRdvController::indexAction'
  methods: [GET, POST]