admin_dimsymphony_config_index:
  path: /modules/dimsymfony/config
  controller: 'DimSymfony\Controller\Admin\AdminDimSymfonyConfigController::indexAction'

admin_dimsymphony_gestionrdv_index:
  path: /modules/dimsymfony/gestionrdv
  controller: 'DimSymfony\Controller\Admin\DimSymfonyGestionRdvController::indexAction'