admin_dimsymphony_config_index:
  path: /modules/dimsymfony/config
  defaults:
    _controller: 'DimSymfony\Controller\Admin\AdminDimSymfonyConfigController::indexAction'
    _legacy_controller: 'AdminModules'
    _legacy_link: 'AdminModules'

admin_dimsymphony_gestionrdv_index:
  path: /modules/dimsymfony/gestionrdv
  defaults:
    _controller: 'DimSymfony\Controller\Admin\DimSymfonyGestionRdvController::indexAction'
    _legacy_controller: 'AdminModules'
    _legacy_link: 'AdminModules'
