configuration_form_simple:
  path: /modules/dimsymfony/configuration
  methods: [GET, POST]
  defaults:
    _controller: 'DimSymfony\Controller\ConfigurationController::index'
    _legacy_controller: 'AdminModules'
    _legacy_link: 'AdminModules'

admin_dimsymphony_gestionrdv_index:
  path: /modules/dimsymfony/gestionrdv
  defaults:
    _controller: 'DimSymfony\Controller\Admin\DimSymfonyGestionRdvController::indexAction'
    _legacy_controller: 'AdminModules'
    _legacy_link: 'AdminModules'