configuration_form_simple:
  path: /modules/dimsymfony/configuration
  methods: [GET, POST]
  defaults:
    _controller: 'DimSymfony\Controller\ConfigurationController::index'
    _legacy_controller: 'DimSymfony'
    _legacy_link: 'DimSymfony'