services:
  _defaults:
    public: true

  # Register the controllers
  DimSymfony\Controller\Admin\DimSymfonyGestionRdvController:
    arguments:
      - '@Dimsymfony.service.itinerary_service'
      - '%dimsymphony.google_api_key%'
    tags:
      - { name: 'controller.service_arguments' }
      - { name: 'admin_module' } # Add this tag
      

  DimSymfony\Controller\Admin\AdminDimSymfonyConfigController:
    # Now inject the correct service that exists:
    arguments:
      - '@prestashop.module.dimsymfony.form.configuration_text_form_data_handler'
    tags: ['controller.service_arguments', 'admin_module']

  # Demo configuration text form
  prestashop.module.dimsymfony.form.type.configuration_text:
    class: DimSymfony\Form\ConfigurationFormType
    parent: form.type.translatable.aware
    public: true
    tags:
      - { name: form.type }

  prestashop.module.dimsymfony.form.configuration_text_data_configuration:
    class: DimSymfony\Form\ConfigurationTextDataConfiguration
    arguments:
      - '@prestashop.adapter.legacy.configuration'

  prestashop.module.dimsymfony.form.configuration_text_form_data_provider:
    class: DimSymfony\Form\ConfigurationTextFormDataProvider
    arguments:
      - '@prestashop.module.dimsymfony.form.configuration_text_data_configuration'

  prestashop.module.dimsymfony.form.configuration_text_form_data_handler:
    class: PrestaShop\PrestaShop\Core\Form\Handler
    arguments:
      - '@form.factory'
      - '@prestashop.core.hook.dispatcher'
      - '@prestashop.module.dimsymfony.form.configuration_text_form_data_provider'
      - 'DimSymfony\Form\ConfigurationFormType'
      - 'Configuration'

  Dimsymfony.service.itinerary_service:
    class: DimSymfony\Service\ItineraryService

parameters:
  dimsymphony.google_api_key: '%env(DIMSYMFONY_GOOGLE_API_KEY)%'
